
mysql:
  image: openzipkin/zipkin-mysql:1.33.0
  ports:
    - 3306:3306
query:
  image: openzipkin/zipkin-java:0.5.2
  environment:
    - STORAGE_TYPE=mysql
  ports:
    - 9411:9411
  links:
    - mysql:storage
web:
  image: openzipkin/zipkin-web:1.33.0
  ports:
    - 8080:8080
  environment:
    - TRANSPORT_TYPE=http
  links:
    - query
